### ISSUE TITLE
Error "Not found" after login

### ISSUE THREAD

**Issue by robert-scheck** [cockpit-project/cockpit-container#14]
I'm only getting "Not found" error message after login (according to the HTML source code it's generated by cockpit). Steps:

  * `yum install atomic cockpit-bridge` (CentOS 7.4)
  * `atomic install cockpit/ws`
  * `atomic run cockpit/ws`
  * Opened `https://<ip>:9090/` in browser
  * Successful login using `root`
  * "Not found" error

**Comment by martinpitt** [comment]
You need to install (at least) `cockpit-system` too.

**Comment by robert-scheck** [comment]
If I need to install `cockpit-bridge` and (at least) `cockpit-system` anyway on the host system, what's the benefit of `cockpit-ws` inside a container? Or do I overlook something…

**Comment by martinpitt** [comment]
Well, you don't need cockpit-ws on the host. This is the "active" part, i. e. the package with the systemd service/socket, opening the port, SSL certificates, etc. Fedora/RHEL Atomic have cockpit-{bridge,system,ostree} preinstalled in the ostree, but not the web server.
