### ISSUE TITLE
[Question] Accessing via reverse proxy container?

### ISSUE THREAD

**Issue by liquidat** [cockpit-project/cockpit-container#18]
Is it possible at all to access the cockpit container from a reverse proxy running on the same docker daemon? 

The idea is to offload things like routing (cockpit.example.com:443 -> cockpit-container:9090) and letsencrypt certificate management to other sources like traefik, ngingx, etc.

I did manage to bring up the container which was quite easy. However, upon calling the appropriate address the error is always "Bad Gateway" and I begin to wonder if this is not an error on my setup but a missing feature in general.

**Comment by brettinternet** [comment]
This is a stale issue, but for anyone else that finds a way here:

See the project tech lead's remarks regarding dockerized Cockpit [here](https://github.com/cockpit-project/cockpit/issues/10458#issuecomment-434608464). It looks like you want to setup a containerized cockpit/ws as a bastion host connecting to the host's cockpit service? Then you could reverse proxy within your container orchestration using something like Traefik. I suppose you should also stop the host's cockpit-ws which is automatically started by systemd on boot. Although, if you're not on Atomic, I believe you'll have to set up your own Dockerfile.

**Comment by liquidat** [comment]
@brettinternet Thanks for coming back to this and the link to the other issue, I will look into it!
My request by the way was to connect to the cockpit on the very same machine, not as a bastion host.
