### ISSUE TITLE
Certificate/smart card authentication with cockpit/ws image

### ISSUE THREAD

**Issue by mkerins** [cockpit-project/cockpit-container#26]
Hello, I'm trying to get certificate/smart card authentication working using the docker image and atomic. Logins using username/password authenticate against the AD domain and work fine. I added:
```
[WebService]
ClientCertAuthentication = true
```
And restarted the service. The browser does not ask which certificate to use. This is on a CentOS 7 host machine so that's probably at least part of the problem. When I run cockpit directly on a CentOS 8 machine it asks for the certificate. -I have not tried running cockpit as a container on the CentOS 8 host-. The other difference I noticed is the process on the CentOS 7 machine is `cockpit-ws` while on CentOS it is `cockpit-tls`. Is it even possible to run cockpit in a container on CentOS 7 assuming everything is mounted properly and support certificate/smart card auth? Every other feature of cockpit does work. Thanks.

EDIT: I followed the instructions here: https://hub.docker.com/r/cockpit/ws to run the container on a CentOS 8 system and it doesn't appear to support certificate/smart card authentication. Probably has to do with running `cockpit-ws` instead of `cockpit-tls`

**Comment by mkerins** [comment]
Spoke with @martinpitt , this is not currently possible so closing.

**Comment by martinpitt** [comment]
Echoing my comment from Youtube: cockpit-tls is currently heavily dependent on systemd, and our container is not a "full OS" container, only an application one. I have some ideas around that for the future, though.
