### ISSUE TITLE
Run container as non-root user

### ISSUE THREAD

**Issue by mkerins** [cockpit-project/cockpit-container#27]
Is it possible to run the cockpit container a non-root user? I understand it has to be run with `--privileged` to work. Thanks.

**Comment by martinpitt** [comment]
Not right now, sorry. This has been on my todo wishlist for a long time. We've had the [bastion container](https://github.com/cockpit-project/cockpit/tree/master/containers/bastion) for a long time which is what you want/need, but it's not an "official" product/container image so far. I'd like to make the cockpit/ws container serve both use cases, and adjust its behaviour depending on whether it's privileged or not.

**Comment by martinpitt** [comment]
This is finally possible as of [Cockpit 272](https://cockpit-project.org/blog/cockpit-272.html). See updated documentation on https://quay.io/repository/cockpit/ws
