### ISSUE TITLE
Connecting to non-default SSH port

### ISSUE THREAD

**Issue by jpf91** [cockpit-project/cockpit-container#29]
Hi,

is it possible to somehow make the interface connect to a port different than 22 by default?

I use cockpit on a CoreOS machine and port 22 already is used by a container to serve files via SFTP/SCP/BORG (that SSHD container is joined to a IPA domain). It uses port 22 so that the port does not have to be specified in clients.

The CoreOS machine itself then runs the SSH for machine administration on a different port and I need cockpit to connect to that one.

The only other, though much more complex solution I can see is to run the SSHD container on completely different IP.

**Comment by martinpitt** [comment]
Both the login page ("Connect to:") and the "add remote host" functionality in the Shell can connect to any arbitrary SSH port, yes. Just specify "hostname:port".
